# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "2"

services:
  springboot-app1:
    build: security-service
    ports:
      - "8089:8080"
    links:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYAPP_JDBC_URL=jdbc:postgresql://postgres:/kafkaConnectDB
      - MYAPP_JDBC_USER=hector15933
      - MYAPP_JDBC_PASS=hector15933
  pagos-service:
    build: pagos-service
    ports:
      - "8090:8082"
    links:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYAPP_JDBC_URL=jdbc:postgresql://postgres:/kafkaConnectDB
      - MYAPP_JDBC_USER=hector15933
      - MYAPP_JDBC_PASS=hector15933
  saldo-service:
    build: saldo-service
    ports:
      - "8092:8081"
    links:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYAPP_JDBC_URL=jdbc:postgresql://postgres:/kafkaConnectDB
      - MYAPP_JDBC_USER=hector15933
      - MYAPP_JDBC_PASS=hector15933
  kafka:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://0:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_TLS_CLIENT_AUTH=none
  
  mysql:
    image: mysql:8.0.4
    restart: always
    environment:
      MYSQL_DATABASE: 'kafkaConnectDB'
      MYSQL_USER: 'hector15933'
      MYSQL_PASSWORD: '5Tsabaean_2'
      MYSQL_ROOT_PASSWORD: '5Tsabaean_2'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
  postgres:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: hector15933     # define credentials
      POSTGRES_PASSWORD: hector15933 # define credentials
      POSTGRES_DB: kafkaConnectDB       # define database
    ports:
      - 5432:5432                 # Postgres port
  mongodb:
    image: mongo:5.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "hector15933"
      MONGO_INITDB_ROOT_PASSWORD: "5Tsabaean_2"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
volumes:
  kafka_data:
    driver: local
  mysql_data:
    driver: local
  mongodb_data:
    driver: local
  springboot-app1:
    driver: local
  pagos-service:
    driver: local
  saldo-service:
    driver: local
